"""The schema for our PostgresDB"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/db/schema.ipynb.

# %% auto 0
__all__ = ['TaskStates', 'Task']

# %% ../../nbs/db/schema.ipynb 2
from uuid import UUID, uuid4
from enum import StrEnum
import typing as t
from datetime import datetime

from sqlmodel import Field, SQLModel, Column, JSON

# %% ../../nbs/db/schema.ipynb 3
class TaskStates(StrEnum):
    PENDING = "pending"
    CLAIMED = "claimed"
    COMPLETED = "completed"

# %% ../../nbs/db/schema.ipynb 5
class Task(SQLModel, table=True):
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    state: TaskStates = Field(default=TaskStates.PENDING)
    name: t.Optional[str] = None
    added: datetime = Field(default_factory=datetime.utcnow)
    finished: t.Optional[datetime] = Field(default=None)
    payload: t.Dict[str, t.Any] = Field(default={}, sa_column=Column(JSON))
