# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/openSQS',
                'doc_host': 'https://jjmachan.github.io',
                'git_url': 'https://github.com/jjmachan/openSQS',
                'lib_path': 'openSQS'},
  'syms': {'openSQS.core': {'openSQS.core.foo': ('core.html#foo', 'openSQS/core.py')}}}
